# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8fb295dc99384eb0452e2ae85b07173fc649ca086aefad94fa2f93373293d0e5519797d6ed9a8b60b5d23ce361cd348c0cb936aeda8aa034a613f63108e4489

test:
  secret_key_base: f708eb5e92d8775d05bbe5f090733095f7ffe42c0b23cb5f52fe645ff8d07d150fa2c429d6def12bfe266c64680210e8063fb386ce02a464b0d05ddcc7a8fcd8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
